### PR TITLE
Frontend: Validate: ValidationTable: Add error messages inline

### LINKED ISSUE #39: Add in-line error component
As a data entry person, I want to see any errors associated with a specific data point displayed directly in-line with an error code and description of what's wrong, so that I can easily identify what needs correcting and whether it's a typo that I can fix at my desk or something that needs to be checked in the field.

Use Storybook #36 to create and test in-line error component without proper backend.

### PR DESCRIPTION
**Pull request by illume**
So that the error messages are shown below the row with the error.

Fixes https://github.com/ForestGeoHack/ForestGEO/issues/39
`npm run storybook`

image

### CODE REVIEW

File: FrontEnd/src/components/Validate/Validate.tsx [hunk 1]
```diff
@@ -68,9 +68,18 @@ export function ValidatePure({
       return (
         <>
           <ValidationTable
-            error={true}
             errorMessage={errorsData}
             uploadedData={filesWithErrorsList}
+            headers={[
```
Comment (illume) [inline FrontEnd/src/components/Validate/Validate.tsx:73]: These were hardcoded in another spot of the codebase before. At some point these should not be hardcoded, but it's out of scope for this PR.

**Review by siddheshraze — APPROVED** [review]
